# Этот файл представляет собой сценарий работы телеграм-бота
title = "Test script"
version = "0.1"
last-modification = "2025.06.29.11:00"

commands = ["start", "help"]

[variables]
age = 0
height = 0
weight = 0

[technical.on_reload]
message = 'Бот был перезагружен! Если вы были в каком-то сценарии, то сейчас вам надо будет запустить его заново.'

[technical.on_no_script]
message = 'Извините! У меня сейчас не запущен ни один сценарий!'

[technical.on_out_of_scenary]
message = 'Извините, но я не умею отвечать на сообщения выходящие за рамки сценария.'

[technical.unknown_command]
message = 'Извините, но я не знаю такой команды. Попробуйте /start или /help'

[node.help]
message = 'Помощь пока не оказываю'

[node.start]
message = '''
Привет!
Я волшебный бот!
'''
wait = 1
next = "1"

[node.1]
choice.text = "Выбери вариант ответа:"
choice.answers = [
    ["no", "2"],
    ["yes", "3"],
]

[node.2]
range.text = "Пожалуйста выбери уровень:"
range.values = [1,2,3,4,5]
range.variable = "age"
range.next = "4"

[node.3]
input.text = "Пожалуйста, напишите ваш вес!"
input.type = "number"
input.variable = "weight"
input.next = "4"

[node.4]
message = '''
Спасибо!

Ваши данные:
вес: {weight}
озраст: {age}
'''
end = true
