# Этот файл представляет собой сценарий работы телеграм-бота
title = "Test script"
version = "0.1"
last-modification = "2025.06.29.11:00"
commands = ["start", "help"]

[variables]
poll_1_symptoms = "number"
var_age = "number"
var_height = "number"
var_weight = "number"
var_round = "number"
var_steps = "number"
var_sports = "number"
var_erection = "number"
var_cancer = "number"
var_diabetes = "number"
var_stroke = "number"
var_job = "number"
var_check = "number"
var_score_total = "number"
var_bmi = "number"



# ==================================================================================================================== #
# Технические ноды



[technical.on_reload]
type = "message"
text = 'Бот был перезагружен! Если вы были в каком-то сценарии, то сейчас вам надо будет запустить его заново.'

[technical.on_no_script]
type = "message"
text = 'Извините! У меня сейчас не запущен ни один сценарий!'

[technical.on_out_of_scenary]
type = "message"
text = 'Извините, но я не умею отвечать на сообщения выходящие за рамки сценария.'

[technical.unknown_command]
type = "message"
text = 'Извините, но я не знаю такой команды. Попробуйте /start или /help'



# ==================================================================================================================== #
# Основные сценарии ноды



# Сценарий помощи
[node.help]
type = "message"
text = 'Помощь пока не оказываю'



# Сценарий подготовки чекапа (главный)
[node.start]
type = "message"
text = '''
Привет!
Я чекап-бот и моя задача задать тебя ряд вопросов для определения, нужен ли тебе чекап, и, если да, то на сколько срочно, а так же собрать о тебе необходимые для чекапа данные.

*Чекап — это комплексная оценка здоровья на фоне ощущения здоровья для оценки своего состояния организма и выявления факторов риска развития болезней или болезней на доклиническом этапе (когда вы ничего не ощущаете).
'''
next = "check-up-1"

[node.check-up-1]
type = "wait"
show_status = true
time = 0.5
next = "check-up-2"

[node.check-up-2]
type = "message"
text = '''
Я задам тебе три набора вопросов:
1. Сначала небольшой опрос, чтобы определить, будет ли чекап эффективен в данный момент
2. Набор вопросов, чтобы составить твой профиль и оценить необходимость чекапа.
3. Наконец - вопросы для оценки симптомов старения у мужчин.
'''
next = "check-up-3"

[node.check-up-3]
type = "wait"
show_status = true
time = 0.5
next = "check-up-4"

[node.check-up-4]
type = "choice"
text = 'Готов начать?'
answers = [
    ["нет", "check-up-end-1"],
    ["да", "check-up-5"],
]

    [node.check-up-end-1]
    type = "message"
    text = '''
    Как скажете!

    Если вы все же захотите пройти опров - введите /start
    Если вы хотите узнать подробности о боте - введите /help
    '''
    next = "check-up-end"

[node.check-up-5]
type = "selection"
text = '''
Выберете один или несколько вариантов.

Есть или были ли у вас в ближайшие три месяца:
'''
multiple = true
options =[
    ["Острые инфекции (грипп, острый простатит, COVID-19, ОРВИ, ангина и др.)", "poll_1_symptoms"],
    ["Обострение хронического заболевания? (диабет, гипертония, гастрит, простатит и т. д.)", "poll_1_symptoms"],
    ["Операция или серьёзная травма?", "poll_1_symptoms"],
    ["Сильное ухудшение самочувствия?", "poll_1_symptoms"],
    ["Ничего из выше перечисленного", ""]
]
next = "check-up-6"

[node.check-up-6]
type = "condition"
conditions = [
    ["poll_1_symptoms > 0", "check-up-end-2"]
]
default = "check-up-7"

    [node.check-up-end-2]
    type = "message"
    text = '''
    К сожалению это означает, что сейчас чекап для вас будет неэффективен.
    Вам стоит подождать пару-тройку месяцев, пока ваш организм не восстановатся.
    Возможно вам стоит обратится к врачу.
    '''
    next = "check-up-end"

[node.check-up-7]
type = "message"
text = "Отлично, у вас нет никаких противопоказаний к проведению чекапа!"
next = "check-up-8"

[node.check-up-8]
type = "wait"
show_status = true
time = 0.5
next = "check-up-9"

[node.check-up-9]
type = "message"
text = '''
Давайте теперь оценим, насколько чекап вам сейчас нужен!

Для этого я должен собрать о вас определенные данные.
Всего 10 вопросов.
'''
next = "check-up-10"

[node.check-up-10]
type = "wait"
show_status = true
time = 0.5
next = "check-up-11"

[node.check-up-11]
type = "input"
text = "Вопрос 1/10\nПожалуйста напишите ваш возраст"
variable = "var_age"
next = "check-up-12"

[node.check-up-12]
type = "input"
text = "Вопрос 2/10\nНапишите ваш рост в сантиметрах (одна цифра)"
variable = "var_age"
next = "check-up-13"

[node.check-up-13]
type = "input"
text = "Вопрос 2/10\nНапишите ваш рост в сантиметрах (одна цифра)"
variable = "var_height"
next = "check-up-14"

[node.check-up-14]
type = "input"
text = "Вопрос 3/10\nНапишите ваш вес в килограммах (одна цифра)"
variable = "var_weight"
next = "check-up-15"

[node.check-up-15]
type = "input"
text = "Вопрос 4/10\nНапишите вашу окружность талии в сантиметрах (одна цифра)"
variable = "var_round"
next = "check-up-16"

[node.check-up-16]
type = "range"
text = '''
Вопрос 5/10
Пожалуйста оцените вашу физическую активность:
Как много шагов вы ходите в день (усредненно)
'''
values = [
    ["менее 1000 шагов", 1000],
    ["3000-5000 шагов", 5000],
    ["5000-9000 шагов", 9000],
    ["более 9000 шагов", 10000],
]
variable = "var_steps"
next = "check-up-17"

[node.check-up-17]
type = "message"
text = "Отлично! Половина пути пройдена!"
next = "check-up-18"

[node.check-up-18]
type = "wait"
show_status = true
time = 0.5
next = "check-up-19"

[node.check-up-19]
type = "range"
text = '''
Вопрос 6/10
Оцените, как часто вы занимаетесь спортом/тренируетесь в спортзале?
'''
values = [
    ["никогда", 0],
    ["1-2 раза в неделю", 2],
    ["3-5 раз в неделю", 5],
    ["постоянно", 7],
]
variable = "var_sports"
next = "check-up-20"

[node.check-up-20]
type = "range"
text = '''
Вопрос 7/10
Есть ли проблемы с эрекций?
'''
values = [
    ["никогда", 0],
    ["редко", 1],
    ["часто", 2],
    ["постоянно", 3],
]
variable = "var_erection"
next = "check-up-21"

[node.check-up-21]
type = "selection"
text = '''
Вопрос 8/10
Есть ли наследственные болезни?
'''
multiple = true
options =[
    ["рак у кровных родственников", "var_cancer"],
    ["Сахарный диабет", "var_diabetes"],
    ["инсульты, инфаркты в возрасте до 55 лет", "var_stroke"]
]
next = "check-up-22"

[node.check-up-22]
type = "range"
text = '''
Вопрос 9/10
У вас сидячая работа? Как долго вы сидите в рабочее время?
'''
values = [
    ["весь день", 3],
    ["5-6 часов", 2],
    ["2-3 часа", 1],
    ["не сижу", 0],
]
variable = "var_job"
next = "check-up-23"

[node.check-up-23]
type = "range"
text = '''
Вопрос 10/10
Проходили ли вы чекап в последние три года?
'''
values = [
    ["нет", 0],
    ["да", 1]
]
variable = "var_check"
next = "check-up-24"

[node.check-up-24]
type = "message"
text = '''
Отлично, спасибо!
Этих данных достаточно что бы оценить вашу потребность в чекапе.
'''
next = "check-up-25"

#var_height = "number"
#var_weight = "number"
#var_round = "number"
#var_steps = "number"
#var_sports = "number"
#var_erection = "number"
#var_cancer = "number"
#var_diabetes = "number"
#var_stroke = "number"
#var_job = "number"
#var_check = "number"
#var_score_total = "number"
# Мы собрали все данные - рассчитываем итоговые значения!
[node.check-up-25]
type = "calculate"
expressions = [
    ["var_bmi", "var_weight / ( var_height * var_height * 0.0001 )"],
    ["var_score_total", "0"]
]
next = "check-up-26"

[node.check-up-26]
type = "condition"
conditions = [
    ["var_score_total < 2", "check-up-end-3"],
    ["var_score_total < 5", "check-up-end-3"]
]
default = "check-up-27"

    [node.check-up-end-3]
    type = "message"
    text = "Чекап не нужен, организм в балансе. В настоящий момент имеющиеся чекапы здоровья для вас не имеют эффективности по сравнению с потенциальным вредом (гипердиагностика - выявление болезней и состояний, которые никогда не скажутся на вашем здоровье)"
    next = "check-up-end"

[node.check-up-27]
text = '''
У вас есть факторы риска!
Чекап желателен. Имеются факторы риска, которые, потенциально, при длительном воздействии могут приводить к развитию болезней.
'''
next = "check-up-29"

[node.check-up-28]
text = '''
У ВАС ЕСТЬ ФАКТОРЫ РИСКА
Имеются достаточно факторов риска для прохождения чекапов здоровья в ближайшее время. Необходимо вовремя выявить присутствие предболезней, состояний, когда болезнь еще можно дезактивировать.
'''
next = "check-up-29"

[node.check-up-29]
type = "choice"
text = '''
Если вы хотите продолжить и записаться на чекап - то осталось ответить на еще один небольшой опрос (5 вопросов) для оценки симптомов старения.

После этого ваши данные будут направлены доктору и с вами свяжутся.

Готовы?
'''
answers = [
    ["нет", "check-up-end-1"],
    ["да", "check-up-5"],
]





[node.check-up-end]
type = "end"









    Чекап не нужен, организм в балансе. В настоящий момент имеющиеся чекапы здоровья для вас не имеют эффективности по сравнению с потенциальным вредом (гипердиагностика - выявление болезней и состояний, которые никогда не скажутся на вашем здоровье)

    У вас есть факторы риска!
    Чекап желателен. Имеются факторы риска, которые, потенциально, при длительном воздействии могут приводить к развитию болезней.

    У ВАС ЕСТЬ ФАКТОРЫ РИСКА
    Имеются достаточно факторов риска для прохождения чекапов здоровья в ближайшее время. Необходимо вовремя выявить присутствие предболезней, состояний, когда болезнь еще можно дезактивировать

    ЗАПИСЬ НА ОН-ЛАЙН КОНСУЛЬТАЦИЮ ИЛИ ОЧНЫЙ ОСМОТР ТГ: телеграм Доктор Борисов



Если вы хотите продолжить и записаться на чекап - то осталось ответить на еще один небольшой опрос (5 вопросов) для оценки симптомов старения.

После этого ваши данные будут направлены доктору и с вами свяжутся.

Готовы?
да / нет



AMS - Оценка симптомов старения у мужчин
На каждый вопрос выберете от 1 до 5 где
1 - нет симптомов
2 - лёгкий
3 - умеренный
4 - выраженный
5 - крайне выраженный.


Вопрос 1/5
Оцените Общее снижение самочувствия (физического/эмоционального)

Вопрос 2/5
Оцените Тревожность, раздражительность, напряжение.

Вопрос 3/5
Оцените Усталость, снижение энергии, упадок сил.

Вопрос 4/5
Оцените Снижение концентрации, памяти, умственных способностей.

Вопрос 5/5
Оцените Подавленность, плохое настроение.