# Этот файл представляет собой сценарий работы телеграм-бота
title = "Test script"
last-modification = "2025.06.29.11:00"

# Секция variables содержит в себе список переменных, с которыми работает сценарий
[variables]
is_quiz_completed = false
age = 0
height = 0
weight = 0

# секция commands содержит набор команд с указанием шага, который нужно запустить
[commands]
start = "quiz_start"

# блоки [node.xxx] представляют из себя конкретные шаги сценария
# каждый шаг должен иметь свой уникальный идентификатор xxx
# идентификатор может состоять из букв, цифр и _ прочерка
[node.quiz_start]
condition = [
    ["is_quiz_completed", "0", "2"]
]

[node.quiz1]
message = "Вы уже прошли опрос. Желаете начать его снова?"
buttons = [
    { "нет" = "1" },
    { "да" = "2" },
]

[node.quiz2]
message = ""

[node.quiz3]
text = "this is third node"
