# Этот файл представляет собой сценарий работы телеграм-бота
title = "Test script"
version = "0.1"
last-modification = "2025.06.29.11:00"
commands = ["start", "help"]

[variables]
poll_1_symptoms = "number"
var_data_collected = "bool"

# profile
var_age = "number"
var_height = "number"
var_weight = "number"
var_round = "number"
var_steps = "number"
var_sports = "number"
var_erection = "number"
var_cancer = "number"
var_diabetes = "number"
var_stroke = "number"
var_job = "number"
var_check = "number"

var_bmi = "number"
var_score_total = "number"

# AMS
var_ams_1 = "number"
var_ams_2 = "number"
var_ams_3 = "number"
var_ams_4 = "number"
var_ams_5 = "number"



# ==================================================================================================================== #
# Технические ноды



[technical.on_reload]
type = "message"
text = 'Бот был перезагружен! Если вы были в каком-то сценарии, то сейчас вам надо будет запустить его заново.'

[technical.on_no_script]
type = "message"
text = 'Извините! У меня сейчас не запущен ни один сценарий!'

[technical.on_out_of_scenary]
type = "message"
text = 'Извините, но я не умею отвечать на сообщения выходящие за рамки сценария.'

[technical.unknown_command]
type = "message"
text = 'Извините, но я не знаю такой команды. Попробуйте /start или /help'



# ==================================================================================================================== #
# Основные сценарии ноды



# Сценарий помощи
[node.help]
type = "message"
text = 'Помощь пока не оказываю'



# Сценарий подготовки чекапа (главный)
[node.start]
type = "message"
text = '''
Привет!
Я чекап-бот и моя задача задать тебя ряд вопросов для определения, нужен ли тебе чекап, и, если да, то на сколько срочно, а так же собрать о тебе необходимые для чекапа данные.

Чекап — это комплексная оценка здоровья на фоне ощущения здоровья для оценки своего состояния организма и выявления факторов риска развития болезней или болезней на доклиническом этапе (когда вы ничего не ощущаете).
'''
next = "pre_check_up_1"

[node.pre_check_up_1]
type = "message"
wait = [0.5, "typing"]
text = '''
Я задам вам три набора вопросов:
1. Сначала небольшой опрос, чтобы определить, будет ли чекап эффективен в данный момент
2. Набор вопросов, чтобы составить твой профиль и оценить необходимость чекапа.
3. Наконец - вопросы для оценки симптомов старения у мужчин.
'''
next = "pre_check_up_2"

[node.pre_check_up_2]
type = "choice"
wait = [0.5, "typing"]
text = 'Готов начать?'
answers = [
    ["нет", "end_1"],
    ["да", "pre_check_up_3"],
]

    [node.end_1]
    type = "message"
    text = '''
Как скажете!

Вы в любое время можете перезапустить этот сценарий отправив мне команы /start

Если вы хотите узнать подробности о боте - введите /help
    '''
    next = "end"

[node.pre_check_up_3]
type = "selection"
wait = [0.5, "typing"]
text = '''
Есть или были ли у вас в ближайшие три месяца:

(выберите один или несколько ответов)
'''
multiple = true
options =[
    ["Острые инфекции (грипп, острый простатит, COVID-19, ОРВИ, ангина и др.)", "poll_1_symptoms"],
    ["Обострение хронического заболевания? (диабет, гипертония, гастрит, простатит и т. д.)", "poll_1_symptoms"],
    ["Операция или серьёзная травма?", "poll_1_symptoms"],
    ["Сильное ухудшение самочувствия?", "poll_1_symptoms"],
    ["Ничего из выше перечисленного", ""]
]
next = "pre_check_up_4"

[node.pre_check_up_4]
type = "condition"
conditions = [
    ["poll_1_symptoms > 0", "end_2"]
]
default = "pre_check_up_5"

    [node.end_2]
    type = "message"
    wait = [0.5, "typing"]
    text = '''
К сожалению это означает, что сейчас чекап для вас будет неэффективен.

У вас уже есть симптомы некоторых болезней (даже если сами болезни уже закончились). И если у вас есть еще какие-то скрытые болезни, то их симптомы будут неопределимы на фоне уже имеющихся симптомов.

Вам стоит подождать пару-тройку месяцев, пока ваш организм не восстановатся.

Вы в любое время можете перезапустить этот сценарий отправив мне команы /start
    '''
    next = "end"

[node.pre_check_up_5]
type = "message"
wait = [0.5, "typing"]
text = "Отлично, у вас нет никаких противопоказаний к проведению чекапа!"
next = "profile_1"

[node.profile_1]
type = "message"
wait = [1.5, "typing"]
text = '''
Давайте теперь оценим, насколько чекап вам сейчас нужен!

Для этого я должен собрать о вас определенные данные.
Всего 10 вопросов.
'''
next = "profile_2"

[node.profile_2]
type = "input"
wait = [0.5, "typing"]
text = "Вопрос 1/10\nПожалуйста напишите ваш возраст"
variable = "var_age"
next = "profile_3"

[node.profile_3]
type = "input"
wait = [0.5, "typing"]
text = "Вопрос 2/10\nНапишите ваш рост в сантиметрах (одна цифра)"
variable = "var_height"
next = "profile_4"

[node.profile_4]
type = "input"
wait = [0.5, "typing"]
text = "Вопрос 3/10\nНапишите ваш вес в килограммах (одна цифра)"
variable = "var_weight"
next = "profile_5"

[node.profile_5]
type = "input"
wait = [0.5, "typing"]
text = "Вопрос 4/10\nНапишите вашу окружность талии в сантиметрах (одна цифра)"
variable = "var_round"
next = "profile_6"

[node.profile_6]
type = "range"
wait = [0.5, "typing"]
text = '''
Вопрос 5/10
Как много шагов вы ходите в день (усредненно)
'''
values = [
    ["менее 1000 шагов", 1000],
    ["3000-5000 шагов", 5000],
    ["5000-9000 шагов", 9000],
    ["более 9000 шагов", 10000],
]
variable = "var_steps"
next = "profile_7"

[node.profile_7]
type = "message"
wait = [0.5, "typing"]
text = "Отлично! Половина пути пройдена!"
next = "profile_8"

[node.profile_8]
type = "range"
wait = [1.0, "typing"]
text = '''
Вопрос 6/10
Оцените, как часто вы занимаетесь спортом/тренируетесь в спортзале?
'''
values = [
    ["никогда", 0],
    ["1-2 раза в неделю", 2],
    ["3-5 раз в неделю", 5],
    ["постоянно", 7],
]
variable = "var_sports"
next = "profile_9"

[node.profile_9]
type = "range"
wait = [0.5, "typing"]
text = '''
Вопрос 7/10
Есть ли проблемы с эрекций?
'''
values = [
    ["никогда", 0],
    ["редко", 1],
    ["часто", 2],
    ["постоянно", 3],
]
variable = "var_erection"
next = "profile_10"

[node.profile_10]
type = "selection"
wait = [0.5, "typing"]
text = '''
Вопрос 8/10
Есть ли наследственные болезни?

(выберите один или несколько ответов)
'''
multiple = true
options =[
    ["рак у кровных родственников", "var_cancer"],
    ["Сахарный диабет", "var_diabetes"],
    ["инсульты, инфаркты в возрасте до 55 лет", "var_stroke"]
]
next = "profile_11"

[node.profile_11]
type = "range"
wait = [0.5, "typing"]
text = '''
Вопрос 9/10
У вас сидячая работа? Как долго вы сидите в рабочее время?
'''
values = [
    ["весь день", 3],
    ["5-6 часов", 2],
    ["2-3 часа", 1],
    ["не сижу", 0],
]
variable = "var_job"
next = "profile_12"

[node.profile_12]
type = "range"
wait = [0.5, "typing"]
text = '''
Вопрос 10/10
Проходили ли вы чекап в последние три года?
'''
values = [
    ["нет", 0],
    ["да", 1]
]
variable = "var_check"
next = "profile_13"

[node.profile_13]
type = "message"
wait = [0.5, "typing"]
text = '''
Отлично, спасибо!
Этих данных достаточно что бы оценить вашу потребность в чекапе.
'''
next = "profile_14"

#var_height = "number"
#var_weight = "number"
#var_round = "number"
#var_steps = "number"
#var_sports = "number"
#var_erection = "number"
#var_cancer = "number"
#var_diabetes = "number"
#var_stroke = "number"
#var_job = "number"
#var_check = "number"
#var_score_total = "number"
# Мы собрали все данные - рассчитываем итоговые значения!
[node.profile_14]
type = "calculate"
wait = [0.5, "typing"]
expressions = [
    ["var_data_collected", "True"],
    ["var_bmi", "var_weight / ( var_height * var_height * 0.0001 )"],
    ["var_score_total", "10"]
]
next = "profile_15"

[node.profile_15]
type = "send_form"
url  = "https://docs.google.com/forms/u/0/d/e/1FAIpQLSdVLrc8nkrPhQXyffCHvNR_JokL3Ri1SrGCgMovTzjf7V95Tg/formResponse"
form = [
    ["entry.2049190339", "@username"],
    ["entry.1909510680", "var_age"],
    ["entry.210876095", "var_height"],
    ["entry.1883094476", "var_weight"],
    ["entry.1253864560", "var_round"],
    ["entry.289557824", "var_steps"],
    ["entry.2127535516", "var_sports"],
    ["entry.1224265442", "var_erection"],
    ["entry.2059824086", "var_cancer"],
    ["entry.267514677", "var_diabetes"],
    ["entry.1771178035", "var_stroke"],
    ["entry.1945850213", "var_job"],
    ["entry.2036286477", "var_check"]
]
next = "profile_16"

[node.profile_16]
type = "condition"
wait = [0.5, "typing"]
conditions = [
    ["var_score_total < 2", "end_3"],
    ["var_score_total < 5", "profile_17"]
]
default = "profile_18"

    [node.end_3]
    type = "message"
    text = "Чекап не нужен, организм в балансе. В настоящий момент имеющиеся чекапы здоровья для вас не имеют эффективности по сравнению с потенциальным вредом (гипердиагностика - выявление болезней и состояний, которые никогда не скажутся на вашем здоровье)"
    next = "end"

[node.profile_17]
type = "message"
text = '''
У вас есть некоторые факторы риска!
Чекап желателен. Имеются факторы риска, которые, потенциально, при длительном воздействии могут приводить к развитию болезней.
'''
next = "profile_19"

[node.profile_18]
type = "message"
text = '''
У ВАС ЕСТЬ ФАКТОРЫ РИСКА
Имеются достаточно факторов риска для прохождения чекапов здоровья в ближайшее время. Необходимо вовремя выявить присутствие предболезней, состояний, когда болезнь еще можно дезактивировать.
'''
next = "profile_19"

[node.profile_19]
type = "choice"
wait = [0.5, "typing"]
text = '''
Если вы хотите продолжить и записаться на чекап - то осталось ответить на еще один небольшой опрос (5 вопросов) для оценки симптомов старения.

После этого ваши данные будут направлены доктору и с вами свяжутся.

Готовы?
'''
answers = [
    ["нет", "end_1"],
    ["да", "symptoms_1"],
]


[node.symptoms_1]
type = "message"
wait = [0.5, "typing"]
text = '''
AMS - Оценка симптомов старения у мужчин

На каждый вопрос выберете от 1 до 5 где
1 - нет симптомов
2 - лёгкий
3 - умеренный
4 - выраженный
5 - крайне выраженный.
'''
next = "symptoms_2"

[node.symptoms_2]
type = "range"
wait = [0.5, "typing"]
text = '''
Вопрос 1/5
Оцените Общее снижение самочувствия (физического/эмоционального)
'''
values = [1,2,3,4,5]
variable = "var_ams_1"
next = "symptoms_3"

[node.symptoms_3]
type = "range"
wait = [0.5, "typing"]
text = '''
Вопрос 2/5
Оцените Тревожность, раздражительность, напряжение.
'''
values = [1,2,3,4,5]
variable = "var_ams_2"
next = "symptoms_4"

[node.symptoms_4]
type = "range"
wait = [0.5, "typing"]
text = '''
Вопрос 3/5
Оцените Усталость, снижение энергии, упадок сил.
'''
values = [1,2,3,4,5]
variable = "var_ams_3"
next = "symptoms_5"

[node.symptoms_5]
type = "range"
wait = [0.5, "typing"]
text = '''
Вопрос 4/5
Оцените Снижение концентрации, памяти, умственных способностей.
'''
values = [1,2,3,4,5]
variable = "var_ams_4"
next = "symptoms_6"

[node.symptoms_6]
type = "range"
wait = [0.5, "typing"]
text = '''
Вопрос 5/5
Оцените Подавленность, плохое настроение.
'''
values = [1,2,3,4,5]
variable = "var_ams_5"
next = "symptoms_7"

# <div jsname="o6bZLc">
# <input type="hidden" name="entry.893737562" value="имя">
# <input type="hidden" name="entry.1849799186" value="2">
# <input type="hidden" name="entry.1947250325" value="3">
# <input type="hidden" name="entry.1729075448" value="3">
# <input type="hidden" name="entry.855973916" value="3">
# <input type="hidden" name="entry.414445729" value="3">
# <input type="hidden" name="dlut" value="1752419877012">
# </div>

[node.symptoms_7]
type = "send_form"
url = "https://docs.google.com/forms/u/0/d/e/1FAIpQLSeZ-WPyFGLOEZUZ92iM3SYWIJ9odi8p0bwNxO5R5dhjLLB9qQ/formResponse"
form = [
    ["entry.893737562", "@username"],
    ["entry.1849799186", "var_ams_1"],
    ["entry.1947250325", "var_ams_2"],
    ["entry.1729075448", "var_ams_3"],
    ["entry.855973916", "var_ams_4"],
    ["entry.414445729", "var_ams_5"]
]
next = "symptoms_8"

[node.symptoms_8]
type = "message"
wait = [0.5, "typing"]
text = '''
Отлично!
К сожалению мой сценарий еще не окончен, так что сейчас я просто отображу собранные данные.

poll_1_symptoms = {poll_1_symptoms}
var_data_collected = {aaaaaaaaaaaa}
var_age = {var_age}
var_height = {var_height}
var_weight = {var_weight}
var_round = {var_round}
var_steps = {var_steps}
var_sports = {var_sports}
var_erection = {var_erection}
var_cancer = {var_cancer}
var_diabetes = {var_diabetes}
var_stroke = {var_stroke}
var_job = {var_job}
var_check = {var_check}
var_bmi = {var_bmi}
var_score_total = {var_score_total}
var_ams_1 = {var_ams_1}
var_ams_2 = {var_ams_2}
var_ams_3 = {var_ams_3}
var_ams_4 = {var_ams_4}
var_ams_5 = {var_ams_5}
'''
next = "symptoms_9"

[node.symptoms_9]
type = "message"
wait = [0.5, "typing"]
text = '''
Тестовый сценарий завершен!

Спасибо что воспользовались нашим ботом!
'''
next = "end"




[node.end]
type = "end"





